FROM fedora:43 AS base

WORKDIR /app

# Prime the yum cache once
RUN yum makecache



FROM base AS pale-moon-tarball

RUN curl -L ftp://ftp.palemoon.org/avx/linux/palemoon-33.9.1.linux-x86_64-sse2_gtk3.tar.xz | tar xJ



FROM base AS flashplayer-tarball

RUN mkdir flashplayer && \
    curl -L https://github.com/darktohka/clean-flash-builds/releases/download/v1.7/flash_player_patched_npapi_linux.x86_64.tar.gz | tar xz -C $_



FROM base AS java_legacy-tarball

RUN mkdir jdk-8u261 && \
    curl -L https://archive.org/download/Java-Archive/Java%20SE%208%20%288u211%20and%20later%29/8u261/JDK/jdk-8u261-linux-x64.tar.gz | tar xz -C $_



FROM base AS desktop

RUN yum -y install \
    xorg-x11-server-Xvfb \
    x11vnc \
    novnc \
    openbox \
    procps-ng \
    less \
    nano \
    hostname \
    gtk2 \
    gtk3 \
    dbus-glib \
    libnsl \
    xterm \
    tini

# Palemoon installation based on https://developer.palemoon.org/docs/linux-installation/
COPY --from=pale-moon-tarball /app/palemoon /app/palemoon
RUN ln -s ${PWD}/palemoon/palemoon /usr/bin/palemoon && \
    mkdir -p /usr/share/icons/hicolor/{16x16,32x32,48x48,128x128}/apps/ && \
    ln -s ${PWD}/palemoon/browser/chrome/icons/default/default16.png /usr/share/icons/hicolor/16x16/apps/palemoon.png && \
    ln -s ${PWD}/palemoon/browser/chrome/icons/default/default32.png /usr/share/icons/hicolor/32x32/apps/palemoon.png && \
    ln -s ${PWD}/palemoon/browser/chrome/icons/default/default48.png /usr/share/icons/hicolor/48x48/apps/palemoon.png && \
    ln -s ${PWD}/palemoon/browser/icons/mozicon128.png /usr/share/icons/hicolor/128x128/apps/palemoon.png && \
    mkdir -p ${HOME}/.moonchild\ productions/pale\ moon/default

RUN cat << EOF > /usr/share/applications/palemoon.desktop
[Desktop Entry]
Version=1.0
Name=Pale Moon Web Browser
Comment=Browse the World Wide Web
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=palemoon %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=palemoon
Categories=Network;WebBrowser;Internet
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
EOF

RUN cat << EOF > ${HOME}/.moonchild\ productions/pale\ moon/profiles.ini
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=default
Default=1
EOF

RUN cat << EOF > ${HOME}/.moonchild\ productions/pale\ moon/default/prefs.js
# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("status4evar.firstRun", false);
EOF


# Flashplayer installation based on https://github.com/darktohka/clean-flash-builds/releases/tag/v1.7
COPY --from=flashplayer-tarball /app/flashplayer/libflashplayer.so /tmp/libflashplayer.so
RUN mkdir -p ${HOME}/.mozilla/plugins && \
    mv /tmp/libflashplayer.so $_


# Java install
COPY --from=java_legacy-tarball /app/jdk-8u261/ /app/java
RUN ln -s /app/java/jdk1.8.0_261/bin/java /usr/bin/java && \
    ln -s /app/java/jdk1.8.0_261/bin/javaws /usr/bin/javaws && \
    ln -s /app/java/jdk1.8.0_261/bin/jcontrol /usr/bin/jcontrol && \
    ln -s /app/java/jdk1.8.0_261/jre/lib/amd64/libnpjp2.so ${HOME}/.mozilla/plugins/libnpjp2.so

RUN cat << EOF > /usr/share/applications/javaws.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Java 8 Web Start
Comment=Java 8 Web Start
Exec=/app/java/jdk1.8.0_261/bin/javaws %u
Terminal=false
Type=Application
Icon=javaws
Categories=Application;Network;
MimeType=application/x-java-jnlp-file;
EOF

RUN mkdir ${HOME}/.config && cat << EOF > ${_}/mimeapps.list
[Added Associations]
application/x-java-jnlp-file=javaws.desktop;
EOF


# The 
RUN cat << "EOF" > /app/startup.sh
#!/bin/bash

set -xeuo pipefail

export DISPLAY=":1"

Xvfb ${DISPLAY} -screen 0 1280x1024x16 &
sleep 3

openbox-session &

x11vnc \
    -display ${DISPLAY} \
    -nopw \
    -listen localhost \
    -xkb \
    -ncache 10 \
    -ncache_cr \
    -forever &

sleep 3

xterm &
palemoon &

exec /usr/bin/novnc_proxy --vnc localhost:5900 --file-only
EOF

RUN chmod +x /app/startup.sh

ENV DISPLAY=":1"
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/app/startup.sh"]
EXPOSE 6080
